---
title: "Checking_Fit"
format: html
editor: visual
---

```{r}
library(tidyverse)
```

```{r}
map_board_df = readxl::read_xlsx('empty_board.xlsx',sheet = 'mapping') %>% 
  mutate(values = sample(4,4)) %>%  ## Determine th values for positions 
  separate(col = top_left_tl,into = c('square_tl','pos_tl','row_tl','col_tl'),
           remove = FALSE) %>% 
  separate(col = top_right_tr,into = c('square_tr','pos_tr','row_tr','col_tr'),
           remove = FALSE) %>% 
  separate(col = bottom_left_bl,into = c('square_bl','pos_bl','row_bl','col_bl'),remove = FALSE) %>% 
  separate(col = bottom_right_br,into = c('square_br','pos_br','row_br','col_br'),remove = FALSE) %>% 
  pivot_longer(top_right_tr:col_bl)


all_possible_df =readxl::read_xlsx('empty_board.xlsx',sheet = 'all_possible_combinations')
```

```{r}
checkSpec = function(spec,df){
  result = df %>% 
    filter(value == spec) %>% 
    pull(values) %>% 
    setequal(1:4)
  return(result)
}

determine_rc = function(specType,df,num_checks = 2) {
  
## Checks just 2 columns and rows
  if(num_checks == 2){
  
  return(checkSpec(paste0(specType,1),df) +
           checkSpec(paste0(specType,2),df)  == 2)
    
  } else if(num_checks == 4){ ## checks all rows and columns
        return(checkSpec(paste0(specType,1),df) +
           checkSpec(paste0(specType,2),df) +
             checkSpec(paste0(specType,3),df) + 
             checkSpec(paste0(specType,4),df) == 4)
    
    }
}


conductAllDetemineChecks = function(df,num_checks = 2){
  
  if(num_checks == 2){
  fiveChecks = determine_rc('C',df) +
    determine_rc('R',df) +
    checkSpec('TR',df) +
    checkSpec('TL',df) +
    checkSpec('BR',df) 
  
  return(fiveChecks == 5)
} else if(num_checks == 4){
  sixChecks = determine_rc('C',df) +
    determine_rc('R',df) +
    checkSpec('TR',df) +
    checkSpec('TL',df) +
    checkSpec('BR',df) +
    checkSpec('BL',df)
  
  return(sixChecks == 6)
}
  
}

```

```{r}
map_board_df %>% 
  filter(!str_detect(name,'br') | !str_detect(name,'bottom_right_br')) %>% 
conductAllDetemineChecks(num_checks = 2)
```

```{r}

map_board_df %>% 
  filter(str_detect(name,'br') | str_detect(name,'bottom_right'))   
  

```

Add the Bottom Left Square to \*map_board_df\*

```{r}
map_board_df %>% 
conductAllDetemineChecks(num_checks = 4)
```
